import { createDateForStocksForThisWeek } from '@helpers/createDateForStocksForThisWeek';
import { createDateForStocksForThisDay } from '@helpers/createDateForStocksForThisDay';
import { createDateForStocksForYear } from '@helpers/createDateForStocksForYear';

import type { Stocks } from './types';

export const STOCKS: Stocks[] = [
	{
		symbol: 'NGVT',
		price: 54.62,
		beta: 1.852,
		volAvg: 230870,
		mktCap: 1979838450,
		lastDiv: 0,
		range: '36.66-66.18',
		changes: -0.18,
		companyName: 'Ingevity Corporation',
		currency: 'USD',
		cik: '0001653477',
		isin: 'US45688C1071',
		cusip: '45688C107',
		exchange: 'New York Stock Exchange',
		exchangeShortName: 'NYSE',
		industry: 'Chemicals - Specialty',
		description:
			"Ingevity Corporation manufactures and sells specialty chemicals and activated carbon materials in North America, the Asia Pacific, Europe, the Middle East, Africa, and South America. The company operates through two segments, Performance Materials and Performance Chemicals. The Performance Materials segment engineers, manufactures, and sells hardwood-based and chemically activated carbon products primarily for use in gasoline vapor emission control systems in cars, motorcycles, trucks, and boats. This segment also produces other activated carbon products for use in various applications, including food, water, beverage, and chemical purification. The Performance Chemicals segment comprises of pavement technologies, industrial specialties, and engineered polymers. It manufactures products derived from crude tall oil and lignin extracted from the kraft pulping process, as well as caprolactone monomers and derivatives derived from cyclohexanone and hydrogen peroxide. This segment's products are used in various applications comprising warm mix paving, pavement preservation, pavement reconstruction and recycling, oil well service additives, oil production, and downstream applications; and adhesives, agrochemical dispersants, lubricants, printing inks, industrial intermediates and oilfield, coatings, resins, elastomers, bioplastics, and medical devices. Ingevity Corporation was founded in 1964 and is headquartered in North Charleston, South Carolina.",
		ceo: 'Mr. John C. Fortson',
		sector: 'Basic Materials',
		country: 'US',
		image: 'https://financialmodelingprep.com/image-stock/NGVT.png',
		type: 'stock',
		modifiedStocks: [
			{
				modifiedDate: createDateForStocksForThisWeek('Sat'),
				priceBefore: 49.8,
				priceAfter: 49.71,
				changes: -0.09,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Fri'),
				priceBefore: 46.8,
				priceAfter: 49.8,
				changes: 3,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Thu'),
				priceBefore: 54,
				priceAfter: 46.8,
				changes: -7.2,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Wed'),
				priceBefore: 53.94,
				priceAfter: 54,
				changes: 0.06,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Tue'),
				priceBefore: 54.9,
				priceAfter: 54.94,
				changes: 0.04,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Mon'),
				priceBefore: 54.8,
				priceAfter: 54.62,
				changes: -0.18,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Sun'),
				priceBefore: 54.62,
				priceAfter: 54.8,
				changes: 0.18,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-1),
				priceBefore: 52.62,
				priceAfter: 52.61,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-2),
				priceBefore: 52.63,
				priceAfter: 52.62,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-6),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('December'),
				priceBefore: 49,
				priceAfter: 54,
				changes: 5,
			},
			{
				modifiedDate: createDateForStocksForYear('August'),
				priceBefore: 60,
				priceAfter: 54,
				changes: -6,
			},
			{
				modifiedDate: createDateForStocksForYear('May'),
				priceBefore: 55,
				priceAfter: 54.63,
				changes: -0.37,
			},
			{
				modifiedDate: createDateForStocksForYear('June'),
				priceBefore: 54.68,
				priceAfter: 54.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('April'),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
		],
	},
	{
		symbol: 'KRE',
		price: 49.71,
		beta: 0.92,
		volAvg: 14127829,
		mktCap: 3036307529,
		lastDiv: 1.58458,
		range: '35.76-54.47',
		changes: 0.69,
		companyName: 'SPDR S&P Regional Banking ETF',
		currency: 'USD',
		cik: '0001064642',
		isin: 'US78464A6982',
		cusip: '78464A698',
		exchange: 'New York Stock Exchange Arca',
		exchangeShortName: 'AMEX',
		industry: 'Asset Management',
		website: null,
		description:
			'In seeking to track the performance of the S&P Regional Banks Select Industry Index (the "index"), the fund employs a sampling strategy. It generally invests substantially all, but at least 80%, of its total assets in the securities comprising the index. The index represents the regional banks segment of the S&P Total Market Index ("S&P TMI")',
		ceo: '',
		sector: 'Financial Services',
		country: 'US',
		image: 'https://financialmodelingprep.com/image-stock/KRE.png',
		type: 'etf',
		modifiedStocks: [
			{
				modifiedDate: createDateForStocksForThisWeek('Sat'),
				priceBefore: 49.8,
				priceAfter: 49.71,
				changes: -0.09,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Fri'),
				priceBefore: 46.8,
				priceAfter: 49.8,
				changes: 3,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Thu'),
				priceBefore: 54,
				priceAfter: 46.8,
				changes: -7.2,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Wed'),
				priceBefore: 53.94,
				priceAfter: 54,
				changes: 0.06,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Tue'),
				priceBefore: 54.9,
				priceAfter: 54.94,
				changes: 0.04,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Mon'),
				priceBefore: 54.8,
				priceAfter: 54.62,
				changes: -0.18,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Sun'),
				priceBefore: 54.62,
				priceAfter: 54.8,
				changes: 0.18,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-1),
				priceBefore: 52.62,
				priceAfter: 52.61,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-2),
				priceBefore: 52.63,
				priceAfter: 52.62,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-6),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('December'),
				priceBefore: 49,
				priceAfter: 54,
				changes: 5,
			},
			{
				modifiedDate: createDateForStocksForYear('August'),
				priceBefore: 60,
				priceAfter: 54,
				changes: -6,
			},
			{
				modifiedDate: createDateForStocksForYear('May'),
				priceBefore: 55,
				priceAfter: 54.63,
				changes: -0.37,
			},
			{
				modifiedDate: createDateForStocksForYear('June'),
				priceBefore: 54.68,
				priceAfter: 54.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('April'),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
		],
	},
	{
		symbol: 'GIS',
		price: 69.79,
		beta: 0.142,
		volAvg: 4240206,
		mktCap: 39399874710,
		lastDiv: 2.36,
		range: '60.33-90.89',
		changes: -0.86,
		companyName: 'General Mills, Inc.',
		currency: 'USD',
		cik: '0000040704',
		isin: 'US3703341046',
		cusip: '370334104',
		exchange: 'New York Stock Exchange',
		exchangeShortName: 'NYSE',
		industry: 'Packaged Foods',
		website: 'https://www.generalmills.com',
		description:
			"General Mills, Inc. manufactures and markets branded consumer foods worldwide. The company operates in five segments: North America Retail; Convenience Stores & Foodservice; Europe & Australia; Asia & Latin America; and Pet. It offers ready-to-eat cereals, refrigerated yogurt, soup, meal kits, refrigerated and frozen dough products, dessert and baking mixes, bakery flour, frozen pizza and pizza snacks, snack bars, fruit and salty snacks, ice cream, nutrition bars, wellness beverages, and savory and grain snacks, as well as various organic products, including frozen and shelf-stable vegetables. It also supplies branded and unbranded food products to the North American foodservice and commercial baking industries; and manufactures and markets pet food products, including dog and cat food. The company markets its products under the Annie's, Betty Crocker, Bisquick, Blue Buffalo, Blue Basics, Blue Freedom, Bugles, Cascadian Farm, Cheerios, Chex, Cinnamon Toast Crunch, Cocoa Puffs, Cookie Crisp, EPIC, Fiber One, Food Should Taste Good, Fruit by the Foot, Fruit Gushers, Fruit Roll-Ups, Gardetto's, Go-Gurt, Gold Medal, Golden Grahams, Häagen-Dazs, Helpers, Jus-Rol, Kitano, Kix, Lärabar, Latina, Liberté, Lucky Charms, Muir Glen, Nature Valley, Oatmeal Crisp, Old El Paso, Oui, Pillsbury, Progresso, Raisin Nut Bran, Total, Totino's, Trix, Wanchai Ferry, Wheaties, Wilderness, Yoki, and Yoplait trademarks. It sells its products directly, as well as through broker and distribution arrangements to grocery stores, mass merchandisers, membership stores, natural food chains, e-commerce retailers, commercial and noncommercial foodservice distributors and operators, restaurants, convenience stores, and pet specialty stores, as well as drug, dollar, and discount chains. The company operates 466 leased and 392 franchise ice cream parlors. General Mills, Inc. was founded in 1866 and is headquartered in Minneapolis, Minnesota.",
		ceo: 'Mr. Jeffrey L. Harmening',
		sector: 'Consumer Defensive',
		country: 'US',
		image: 'https://financialmodelingprep.com/image-stock/GIS.png',
		type: 'bound',
		modifiedStocks: [
			{
				modifiedDate: createDateForStocksForThisWeek('Sat'),
				priceBefore: 49.8,
				priceAfter: 49.71,
				changes: -0.09,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Fri'),
				priceBefore: 46.8,
				priceAfter: 49.8,
				changes: 3,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Thu'),
				priceBefore: 54,
				priceAfter: 46.8,
				changes: -7.2,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Wed'),
				priceBefore: 53.94,
				priceAfter: 54,
				changes: 0.06,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Tue'),
				priceBefore: 54.9,
				priceAfter: 54.94,
				changes: 0.04,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Mon'),
				priceBefore: 54.8,
				priceAfter: 54.62,
				changes: -0.18,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Sun'),
				priceBefore: 54.62,
				priceAfter: 54.8,
				changes: 0.18,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-1),
				priceBefore: 52.62,
				priceAfter: 52.61,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-2),
				priceBefore: 52.63,
				priceAfter: 52.62,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-6),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('December'),
				priceBefore: 49,
				priceAfter: 54,
				changes: 5,
			},
			{
				modifiedDate: createDateForStocksForYear('August'),
				priceBefore: 60,
				priceAfter: 54,
				changes: -6,
			},
			{
				modifiedDate: createDateForStocksForYear('May'),
				priceBefore: 55,
				priceAfter: 54.63,
				changes: -0.37,
			},
			{
				modifiedDate: createDateForStocksForYear('June'),
				priceBefore: 54.68,
				priceAfter: 54.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('April'),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
		],
	},
	{
		symbol: 'AWK',
		price: 127.46,
		beta: 0.624,
		volAvg: 1639401,
		mktCap: 24832012120,
		lastDiv: 3.06,
		range: '113.34-151.24',
		changes: 1.51,
		companyName: 'American Water Works Company, Inc.',
		currency: 'USD',
		cik: '0001410636',
		isin: 'US0304201033',
		cusip: '030420103',
		exchange: 'New York Stock Exchange',
		exchangeShortName: 'NYSE',
		industry: 'Regulated Water',
		website: 'https://www.amwater.com',
		description:
			'American Water Works Company, Inc., through its subsidiaries, provides water and wastewater services in the United States. It offers water and wastewater services to approximately 1,700 communities in 14 states serving approximately 3.4 million active customers. The company serves residential customers; commercial customers, including food and beverage providers, commercial property developers and proprietors, and energy suppliers; fire service and private fire customers; industrial customers, such as large-scale manufacturers, mining, and production operations; public authorities comprising government buildings and other public sector facilities, such as schools and universities; and other utilities and community water and wastewater systems. It also provides water and wastewater services on various military installations; and undertakes contracts with municipal customers, primarily to operate and manage water and wastewater facilities, as well as offers other related services. In addition, the company operates approximately 80 surface water treatment plants; 480 groundwater treatment plants; 160 wastewater treatment plants; 52,500 miles of transmission, distribution, and collection mains and pipes; 1,100 groundwater wells; 1,700 water and wastewater pumping stations; 1,300 treated water storage facilities; and 76 dams. It serves approximately 14 million people with drinking water, wastewater, and other related services in 24 states. American Water Works Company, Inc. was founded in 1886 and is headquartered in Camden, New Jersey.',
		ceo: 'Ms. M. Susan Hardwick',
		sector: 'Utilities',
		country: 'US',
		image: 'https://financialmodelingprep.com/image-stock/AWK.png',
		type: 'stock',
		modifiedStocks: [
			{
				modifiedDate: createDateForStocksForThisWeek('Sat'),
				priceBefore: 49.8,
				priceAfter: 49.71,
				changes: -0.09,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Fri'),
				priceBefore: 46.8,
				priceAfter: 49.8,
				changes: 3,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Thu'),
				priceBefore: 54,
				priceAfter: 46.8,
				changes: -7.2,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Wed'),
				priceBefore: 53.94,
				priceAfter: 54,
				changes: 0.06,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Tue'),
				priceBefore: 54.9,
				priceAfter: 54.94,
				changes: 0.04,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Mon'),
				priceBefore: 54.8,
				priceAfter: 54.62,
				changes: -0.18,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Sun'),
				priceBefore: 54.62,
				priceAfter: 54.8,
				changes: 0.18,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-1),
				priceBefore: 52.62,
				priceAfter: 52.61,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-2),
				priceBefore: 52.63,
				priceAfter: 52.62,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-6),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('December'),
				priceBefore: 49,
				priceAfter: 54,
				changes: 5,
			},
			{
				modifiedDate: createDateForStocksForYear('August'),
				priceBefore: 60,
				priceAfter: 54,
				changes: -6,
			},
			{
				modifiedDate: createDateForStocksForYear('May'),
				priceBefore: 55,
				priceAfter: 54.63,
				changes: -0.37,
			},
			{
				modifiedDate: createDateForStocksForYear('June'),
				priceBefore: 54.68,
				priceAfter: 54.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('April'),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
		],
	},
	{
		symbol: 'ASTE',
		price: 32.56,
		beta: 1.411,
		volAvg: 144290,
		mktCap: 740525104,
		lastDiv: 0.52,
		range: '28.97-56.33',
		changes: -0.6,
		companyName: 'Astec Industries, Inc.',
		currency: 'USD',
		cik: '0000792987',
		isin: 'US0462241011',
		cusip: '046224101',
		exchange: 'NASDAQ Global Select',
		exchangeShortName: 'NASDAQ',
		industry: 'Agricultural - Machinery',
		website: 'https://www.astecindustries.com',
		description:
			'Astec Industries, Inc. designs, engineers, manufactures, and markets equipment and components used primarily in road building and related construction activities in the United States and internationally. The company operates in two segments, Infrastructure Solutions and Materials Solutions. The Infrastructure Solutions segment offers asphalt plants and related components, heaters, concrete dust control systems, asphalt pavers, vaporizers, concrete material handling systems, screeds, heat recovery units, paste back-fill plants, asphalt storage tanks, hot oil heaters, bagging plants, fuel storage tanks, industrial and asphalt burners and systems, custom batch plants, material transfer vehicles, soil stabilizing-reclaiming machinery, blower trucks and trailers, milling machines, soil remediation plants, wood chippers and grinders, pump trailers, concrete batch plants, control systems, liquid terminals, storage equipment and related parts, construction and retrofits, polymer plants, and concrete mixers, as well as engineering and environmental permitting services. This segment provides its products to asphalt producers, highway and heavy equipment contractors, ready mix concrete producers, contractors in the construction and demolition recycling markets, and governmental agencies. The Materials Solutions segment designs and manufactures crushing equipment, mobile plants, bulk material handling solutions, vibrating equipment, screening equipment, electrical control centers, modular plants and systems, conveying equipment, plant automation products, portable plants, and mineral processing equipment, as well as offers consulting and engineering services. Astec Industries, Inc. was incorporated in 1972 and is headquartered in Chattanooga, Tennessee.',
		ceo: 'Mr. Jaco G. van der Merwe',
		sector: 'Industrials',
		country: 'US',
		image: 'https://financialmodelingprep.com/image-stock/ASTE.png',
		type: 'stock',
		modifiedStocks: [
			{
				modifiedDate: createDateForStocksForThisWeek('Sat'),
				priceBefore: 49.8,
				priceAfter: 49.71,
				changes: -0.09,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Fri'),
				priceBefore: 46.8,
				priceAfter: 49.8,
				changes: 3,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Thu'),
				priceBefore: 54,
				priceAfter: 46.8,
				changes: -7.2,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Wed'),
				priceBefore: 53.94,
				priceAfter: 54,
				changes: 0.06,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Tue'),
				priceBefore: 54.9,
				priceAfter: 54.94,
				changes: 0.04,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Mon'),
				priceBefore: 54.8,
				priceAfter: 54.62,
				changes: -0.18,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Sun'),
				priceBefore: 54.62,
				priceAfter: 54.8,
				changes: 0.18,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-1),
				priceBefore: 52.62,
				priceAfter: 52.61,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-2),
				priceBefore: 52.63,
				priceAfter: 52.62,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-6),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('December'),
				priceBefore: 49,
				priceAfter: 54,
				changes: 5,
			},
			{
				modifiedDate: createDateForStocksForYear('August'),
				priceBefore: 60,
				priceAfter: 54,
				changes: -6,
			},
			{
				modifiedDate: createDateForStocksForYear('May'),
				priceBefore: 55,
				priceAfter: 54.63,
				changes: -0.37,
			},
			{
				modifiedDate: createDateForStocksForYear('June'),
				priceBefore: 54.68,
				priceAfter: 54.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('April'),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
		],
	},
	{
		symbol: 'LFMD',
		price: 12.45,
		beta: 1.425,
		volAvg: 651129,
		mktCap: 502556700,
		lastDiv: 0,
		range: '1.46-12.8',
		changes: -0.04,
		companyName: 'LifeMD, Inc.',
		currency: 'USD',
		cik: '0000948320',
		isin: 'US53216B1044',
		cusip: '53216B104',
		exchange: 'NASDAQ Global Market',
		exchangeShortName: 'NASDAQ',
		industry: 'Medical - Pharmaceuticals',
		website: 'https://www.lifemd.com',
		description:
			"LifeMD, Inc. operates as a direct-to-patient telehealth company that connects consumers to healthcare professionals for care across various indications, including concierge care, men's sexual health, dermatology, and others in the United States. The company provides ShapiroMD, a telehealth platform brand that offers access to virtual medical treatment, prescription medications, patented-doctor formulated OTC products, and an FDA approved medical device for male and female hair loss, and female specific topical compounded medications for hair loss; RexMD, a men's telehealth brand that offers virtual medical treatment from licensed providers for a variety of men's health needs; LifeMD Primary Care, a personalized subscription-based virtual primary care platform that provides patients with primary care, urgent care, and chronic care needs, as well as .offers a mobile first platform that incorporates virtual consultations and treatment, prescription medications, diagnostics, and imaging; Cleared, a telehealth brand that provides personalized treatments for allergy, asthma, and immunology; and Nava MD, a female-oriented tele-dermatology and skincare brand that offers virtual medical treatment from dermatologists and other providers. It also offers PDFSimpli, an online software-as-a-service platform that allows users to create, edit, convert, sign, and share PDF documents. LifeMD sells its products directly to consumers and through e-commerce platforms, as well as through third party partner channels. The company was formerly known as Conversion Labs, Inc. and changed its name to LifeMD, Inc. in February 2021. LifeMD, Inc. was founded in 1994 and is headquartered in New York, New York.",
		ceo: 'Mr. Justin  Schreiber',
		sector: 'Healthcare',
		country: 'US',
		image: 'https://financialmodelingprep.com/image-stock/LFMD.png',
		type: 'bound',
		modifiedStocks: [
			{
				modifiedDate: createDateForStocksForThisWeek('Sat'),
				priceBefore: 49.8,
				priceAfter: 49.71,
				changes: -0.09,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Fri'),
				priceBefore: 46.8,
				priceAfter: 49.8,
				changes: 3,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Thu'),
				priceBefore: 54,
				priceAfter: 46.8,
				changes: -7.2,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Wed'),
				priceBefore: 53.94,
				priceAfter: 54,
				changes: 0.06,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Tue'),
				priceBefore: 54.9,
				priceAfter: 54.94,
				changes: 0.04,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Mon'),
				priceBefore: 54.8,
				priceAfter: 54.62,
				changes: -0.18,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Sun'),
				priceBefore: 54.62,
				priceAfter: 54.8,
				changes: 0.18,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-1),
				priceBefore: 52.62,
				priceAfter: 52.61,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-2),
				priceBefore: 52.63,
				priceAfter: 52.62,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-6),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('December'),
				priceBefore: 49,
				priceAfter: 54,
				changes: 5,
			},
			{
				modifiedDate: createDateForStocksForYear('August'),
				priceBefore: 60,
				priceAfter: 54,
				changes: -6,
			},
			{
				modifiedDate: createDateForStocksForYear('May'),
				priceBefore: 55,
				priceAfter: 54.63,
				changes: -0.37,
			},
			{
				modifiedDate: createDateForStocksForYear('June'),
				priceBefore: 54.68,
				priceAfter: 54.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('April'),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
		],
	},
	{
		symbol: 'MP',
		price: 15.9649,
		beta: 2.414,
		volAvg: 3870072,
		mktCap: 2842997462,
		lastDiv: 0,
		range: '12.68-26.529',
		changes: 0.0049,
		companyName: 'MP Materials Corp.',
		currency: 'USD',
		cik: '0001801368',
		isin: 'US5533681012',
		cusip: '553368101',
		exchange: 'New York Stock Exchange',
		exchangeShortName: 'NYSE',
		industry: 'Industrial Materials',
		website: 'https://mpmaterials.com',
		description:
			'MP Materials Corp. owns and operates rare earth mining and processing facilities. It owns and operates the Mountain Pass Rare Earth mine located in the Western Hemisphere. The company holds the mineral rights to the Mountain Pass mine and surrounding areas, as well as intellectual property rights related to the processing and development of rare earth minerals. It offers cerium, lanthanum, neodymium, praseodymium, and samarium. The company was founded in 2017 and is headquartered in Las Vegas, Nevada.',
		ceo: 'Mr. Ryan S. Corbett',
		sector: 'Basic Materials',
		country: 'US',
		image: 'https://financialmodelingprep.com/image-stock/MP.png',
		type: 'bound',
		modifiedStocks: [
			{
				modifiedDate: createDateForStocksForThisWeek('Sat'),
				priceBefore: 49.8,
				priceAfter: 49.71,
				changes: -0.09,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Fri'),
				priceBefore: 46.8,
				priceAfter: 49.8,
				changes: 3,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Thu'),
				priceBefore: 54,
				priceAfter: 46.8,
				changes: -7.2,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Wed'),
				priceBefore: 53.94,
				priceAfter: 54,
				changes: 0.06,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Tue'),
				priceBefore: 54.9,
				priceAfter: 54.94,
				changes: 0.04,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Mon'),
				priceBefore: 54.8,
				priceAfter: 54.62,
				changes: -0.18,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Sun'),
				priceBefore: 54.62,
				priceAfter: 54.8,
				changes: 0.18,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-1),
				priceBefore: 52.62,
				priceAfter: 52.61,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-2),
				priceBefore: 52.63,
				priceAfter: 52.62,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-6),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('December'),
				priceBefore: 49,
				priceAfter: 54,
				changes: 5,
			},
			{
				modifiedDate: createDateForStocksForYear('August'),
				priceBefore: 60,
				priceAfter: 54,
				changes: -6,
			},
			{
				modifiedDate: createDateForStocksForYear('May'),
				priceBefore: 55,
				priceAfter: 54.63,
				changes: -0.37,
			},
			{
				modifiedDate: createDateForStocksForYear('June'),
				priceBefore: 54.68,
				priceAfter: 54.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('April'),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
		],
	},
	{
		symbol: 'LOW',
		price: 232.91,
		beta: 1.124,
		volAvg: 2402845,
		mktCap: 133269238720,
		lastDiv: 4.4,
		range: '181.85-262.49',
		changes: 3.33,
		companyName: "Lowe's Companies, Inc.",
		currency: 'USD',
		cik: '0000060667',
		isin: 'US5486611073',
		cusip: '548661107',
		exchange: 'New York Stock Exchange',
		exchangeShortName: 'NYSE',
		industry: 'Home Improvement',
		website: 'https://www.lowes.com',
		description:
			"Lowe's Companies, Inc., together with its subsidiaries, operates as a home improvement retailer in the United States and internationally. The company offers a line of products for construction, maintenance, repair, remodeling, and decorating. It provides home improvement products, such as appliances, seasonal and outdoor living, lawn and garden, lumber, kitchens and bath, tools, paint, millwork, hardware, flooring, rough plumbing, building materials, décor, lighting, and electrical. It also offers installation services through independent contractors in various product categories; extended protection plans; and in-warranty and out-of-warranty repair services. The company sells its national brand-name merchandise and private brand products to homeowners, renters, and professional customers. As of January 28, 2022, it operated 1,971 home improvement and hardware stores. The company also sells its products through websites comprising Lowes.com and Lowesforpros.com; and through mobile applications. Lowe's Companies, Inc. was founded in 1921 and is based in Mooresville, North Carolina.",
		ceo: 'Mr. Marvin R. Ellison',
		sector: 'Consumer Cyclical',
		country: 'US',
		image: 'https://financialmodelingprep.com/image-stock/LOW.png',
		type: 'stock',
		modifiedStocks: [
			{
				modifiedDate: createDateForStocksForThisWeek('Sat'),
				priceBefore: 49.8,
				priceAfter: 49.71,
				changes: -0.09,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Fri'),
				priceBefore: 46.8,
				priceAfter: 49.8,
				changes: 3,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Thu'),
				priceBefore: 54,
				priceAfter: 46.8,
				changes: -7.2,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Wed'),
				priceBefore: 53.94,
				priceAfter: 54,
				changes: 0.06,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Tue'),
				priceBefore: 54.9,
				priceAfter: 54.94,
				changes: 0.04,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Mon'),
				priceBefore: 54.8,
				priceAfter: 54.62,
				changes: -0.18,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Sun'),
				priceBefore: 54.62,
				priceAfter: 54.8,
				changes: 0.18,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-1),
				priceBefore: 52.62,
				priceAfter: 52.61,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-2),
				priceBefore: 52.63,
				priceAfter: 52.62,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-6),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('December'),
				priceBefore: 49,
				priceAfter: 54,
				changes: 5,
			},
			{
				modifiedDate: createDateForStocksForYear('August'),
				priceBefore: 60,
				priceAfter: 54,
				changes: -6,
			},
			{
				modifiedDate: createDateForStocksForYear('May'),
				priceBefore: 55,
				priceAfter: 54.63,
				changes: -0.37,
			},
			{
				modifiedDate: createDateForStocksForYear('June'),
				priceBefore: 54.68,
				priceAfter: 54.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('April'),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
		],
	},
	{
		symbol: 'VEA',
		price: 49.4242,
		beta: 1.08,
		volAvg: 11692432,
		mktCap: 192739149093,
		lastDiv: 1.638,
		range: '41.48-50.36',
		changes: 0.3142,
		companyName: 'Vanguard Developed Markets Index Fund',
		currency: 'USD',
		cik: '0000923202',
		isin: 'US9219438580',
		cusip: '921943858',
		exchange: 'New York Stock Exchange Arca',
		exchangeShortName: 'AMEX',
		industry: 'Asset Management',
		website: 'http://investor.vanguard.com/etf/profile/VEA',
		description:
			'The fund employs an indexing investment approach designed to track the performance of the FTSE Developed All Cap ex US Index, a market-capitalization-weighted index that is made up of approximately 4022 common stocks of large-, mid-, and small-cap companies located in Canada and the major markets of Europe and the Pacific region. The adviser attempts to replicate the target index by investing all, or substantially all, of its assets in the stocks that make up the index, holding each stock in approximately the same proportion as its weighting in the index.',
		ceo: '',
		sector: 'Financial Services',
		country: 'US',
		image: 'https://financialmodelingprep.com/image-stock/VEA.png',
		type: 'etf',
		modifiedStocks: [
			{
				modifiedDate: createDateForStocksForThisWeek('Sat'),
				priceBefore: 49.8,
				priceAfter: 49.71,
				changes: -0.09,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Fri'),
				priceBefore: 46.8,
				priceAfter: 49.8,
				changes: 3,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Thu'),
				priceBefore: 54,
				priceAfter: 46.8,
				changes: -7.2,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Wed'),
				priceBefore: 53.94,
				priceAfter: 54,
				changes: 0.06,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Tue'),
				priceBefore: 54.9,
				priceAfter: 54.94,
				changes: 0.04,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Mon'),
				priceBefore: 54.8,
				priceAfter: 54.62,
				changes: -0.18,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Sun'),
				priceBefore: 54.62,
				priceAfter: 54.8,
				changes: 0.18,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-1),
				priceBefore: 52.62,
				priceAfter: 52.61,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-2),
				priceBefore: 52.63,
				priceAfter: 52.62,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-6),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('December'),
				priceBefore: 49,
				priceAfter: 54,
				changes: 5,
			},
			{
				modifiedDate: createDateForStocksForYear('August'),
				priceBefore: 60,
				priceAfter: 54,
				changes: -6,
			},
			{
				modifiedDate: createDateForStocksForYear('May'),
				priceBefore: 55,
				priceAfter: 54.63,
				changes: -0.37,
			},
			{
				modifiedDate: createDateForStocksForYear('June'),
				priceBefore: 54.68,
				priceAfter: 54.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('April'),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
		],
	},
	{
		symbol: 'BKR',
		price: 31.82,
		beta: 1.445,
		volAvg: 7886916,
		mktCap: 31756296360,
		lastDiv: 0.84,
		range: '26.96-37.58',
		changes: 0.1,
		companyName: 'Baker Hughes Company',
		currency: 'USD',
		cik: '0001701605',
		isin: 'US05722G1004',
		cusip: '05722G100',
		exchange: 'NASDAQ Global Select',
		exchangeShortName: 'NASDAQ',
		industry: 'Oil & Gas Equipment & Services',
		website: 'https://www.bakerhughes.com',
		description:
			'Baker Hughes Company provides a portfolio of technologies and services to energy and industrial value chain worldwide. It operates through four segments: Oilfield Services (OFS), Oilfield Equipment (OFE), Turbomachinery & Process Solutions (TPS), and Digital Solutions (DS). The OFS segment offers exploration, drilling, wireline, evaluation, completion, production, and intervention services; and drilling and completions fluids, wireline services, downhole completion tools and systems, wellbore intervention tools and services, pressure pumping systems, oilfield and industrial chemicals, and artificial lift technologies for oil and natural gas, and oilfield service companies. The OFE segment provides subsea and surface wellheads, pressure control and production systems and services, flexible pipe systems for offshore and onshore applications, and life-of-field solutions, including well intervention and decommissioning solutions; and services related to onshore and offshore drilling and production operations. The TPS segment provides equipment and related services for mechanical-drive, compression, and power-generation applications across the oil and gas industry. Its product portfolio includes drivers, compressors, and turnkey solutions; and pumps, valves, and compressed natural gas and small-scale liquefied natural gas solutions. This segment serves upstream, midstream, downstream, onshore, offshore, and industrial customers. The DS segment provides sensor-based process measurements, machine health and condition monitoring, asset strategy and management, control systems, as well as non-destructive testing and inspection, and pipeline integrity solutions. The company was formerly known as Baker Hughes, a GE company and changed its name to Baker Hughes Company in October 2019. Baker Hughes Company is based in Houston, Texas.',
		ceo: 'Mr. Lorenzo  Simonelli',
		sector: 'Energy',
		country: 'US',
		image: 'https://financialmodelingprep.com/image-stock/BKR.png',
		type: 'bound',
		modifiedStocks: [
			{
				modifiedDate: createDateForStocksForThisWeek('Sat'),
				priceBefore: 49.8,
				priceAfter: 49.71,
				changes: -0.09,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Fri'),
				priceBefore: 46.8,
				priceAfter: 49.8,
				changes: 3,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Thu'),
				priceBefore: 54,
				priceAfter: 46.8,
				changes: -7.2,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Wed'),
				priceBefore: 53.94,
				priceAfter: 54,
				changes: 0.06,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Tue'),
				priceBefore: 54.9,
				priceAfter: 54.94,
				changes: 0.04,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Mon'),
				priceBefore: 54.8,
				priceAfter: 54.62,
				changes: -0.18,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Sun'),
				priceBefore: 54.62,
				priceAfter: 54.8,
				changes: 0.18,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-1),
				priceBefore: 52.62,
				priceAfter: 52.61,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-2),
				priceBefore: 52.63,
				priceAfter: 52.62,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-6),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('December'),
				priceBefore: 49,
				priceAfter: 54,
				changes: 5,
			},
			{
				modifiedDate: createDateForStocksForYear('August'),
				priceBefore: 60,
				priceAfter: 54,
				changes: -6,
			},
			{
				modifiedDate: createDateForStocksForYear('May'),
				priceBefore: 55,
				priceAfter: 54.63,
				changes: -0.37,
			},
			{
				modifiedDate: createDateForStocksForYear('June'),
				priceBefore: 54.68,
				priceAfter: 54.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('April'),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
		],
	},
	{
		symbol: 'PENN',
		price: 15.3427,
		beta: 2.06,
		volAvg: 6095680,
		mktCap: 2330049821,
		lastDiv: 0,
		range: '13.5-29.38',
		changes: 0.3427,
		companyName: 'PENN Entertainment, Inc.',
		currency: 'USD',
		cik: '0000921738',
		isin: 'US7075691094',
		cusip: '707569109',
		exchange: 'NASDAQ Global Select',
		exchangeShortName: 'NASDAQ',
		industry: 'Gambling, Resorts & Casinos',
		website: 'https://www.pennentertainment.com',
		description:
			"PENN Entertainment, Inc., together with its subsidiaries, provides integrated entertainment, sports content, and casino gaming experiences in North America. The company operates through five segments: Northeast, South, West, Midwest, and Interactive. It operates 44 properties in 20 states; online sports betting in 13 jurisdictions; and iCasino in five under a portfolio of brands, including Hollywood Casino, L'Auberge, Barstool Sportsbook, and theScore Bet. The company was formerly known as Penn National Gaming, Inc. and changed its name to PENN Entertainment, Inc. in August 2022. PENN Entertainment, Inc. was founded in 1972 and is based in Wyomissing, Pennsylvania.",
		ceo: 'Mr. Jay A. Snowden',
		sector: 'Consumer Cyclical',
		country: 'US',
		image: 'https://financialmodelingprep.com/image-stock/PENN.png',
		type: 'stock',
		modifiedStocks: [
			{
				modifiedDate: createDateForStocksForThisWeek('Sat'),
				priceBefore: 49.8,
				priceAfter: 49.71,
				changes: -0.09,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Fri'),
				priceBefore: 46.8,
				priceAfter: 49.8,
				changes: 3,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Thu'),
				priceBefore: 54,
				priceAfter: 46.8,
				changes: -7.2,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Wed'),
				priceBefore: 53.94,
				priceAfter: 54,
				changes: 0.06,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Tue'),
				priceBefore: 54.9,
				priceAfter: 54.94,
				changes: 0.04,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Mon'),
				priceBefore: 54.8,
				priceAfter: 54.62,
				changes: -0.18,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Sun'),
				priceBefore: 54.62,
				priceAfter: 54.8,
				changes: 0.18,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-1),
				priceBefore: 52.62,
				priceAfter: 52.61,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-2),
				priceBefore: 52.63,
				priceAfter: 52.62,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-6),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('December'),
				priceBefore: 49,
				priceAfter: 54,
				changes: 5,
			},
			{
				modifiedDate: createDateForStocksForYear('August'),
				priceBefore: 60,
				priceAfter: 54,
				changes: -6,
			},
			{
				modifiedDate: createDateForStocksForYear('May'),
				priceBefore: 55,
				priceAfter: 54.63,
				changes: -0.37,
			},
			{
				modifiedDate: createDateForStocksForYear('June'),
				priceBefore: 54.68,
				priceAfter: 54.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('April'),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
		],
	},
	{
		symbol: 'KC',
		price: 3.4254,
		beta: 2.129,
		volAvg: 1268069,
		mktCap: 813440576,
		lastDiv: 0,
		range: '2.34-7.42',
		changes: -0.0646,
		companyName: 'Kingsoft Cloud Holdings Limited',
		currency: 'USD',
		cik: '0001795589',
		isin: 'US49639K1016',
		cusip: '49639K101',
		exchange: 'NASDAQ Global Select',
		exchangeShortName: 'NASDAQ',
		industry: 'Software - Application',
		website: 'https://www.ksyun.com',
		description:
			"Kingsoft Cloud Holdings Limited provides cloud services to businesses and organizations in China. The company offers public cloud services to customers in various verticals, including game, video, AI, e-commerce, education, and mobile internet; and enterprise cloud services to customers in financial service, public service, and healthcare businesses. The company was incorporated in 2012 and is headquartered in Beijing, the People's Republic of China.",
		ceo: 'Mr. Tao  Zou',
		sector: 'Technology',
		country: 'CN',
		image: 'https://financialmodelingprep.com/image-stock/KC.png',
		type: 'bound',
		modifiedStocks: [
			{
				modifiedDate: createDateForStocksForThisWeek('Sat'),
				priceBefore: 49.8,
				priceAfter: 49.71,
				changes: -0.09,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Fri'),
				priceBefore: 46.8,
				priceAfter: 49.8,
				changes: 3,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Thu'),
				priceBefore: 54,
				priceAfter: 46.8,
				changes: -7.2,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Wed'),
				priceBefore: 53.94,
				priceAfter: 54,
				changes: 0.06,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Tue'),
				priceBefore: 54.9,
				priceAfter: 54.94,
				changes: 0.04,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Mon'),
				priceBefore: 54.8,
				priceAfter: 54.62,
				changes: -0.18,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Sun'),
				priceBefore: 54.62,
				priceAfter: 54.8,
				changes: 0.18,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-1),
				priceBefore: 52.62,
				priceAfter: 52.61,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-2),
				priceBefore: 52.63,
				priceAfter: 52.62,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-6),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('December'),
				priceBefore: 49,
				priceAfter: 54,
				changes: 5,
			},
			{
				modifiedDate: createDateForStocksForYear('August'),
				priceBefore: 60,
				priceAfter: 54,
				changes: -6,
			},
			{
				modifiedDate: createDateForStocksForYear('May'),
				priceBefore: 55,
				priceAfter: 54.63,
				changes: -0.37,
			},
			{
				modifiedDate: createDateForStocksForYear('June'),
				priceBefore: 54.68,
				priceAfter: 54.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('April'),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
		],
	},
	{
		symbol: 'ZURA',
		price: 4.46,
		beta: 0.54,
		volAvg: 311519,
		mktCap: 277973960,
		lastDiv: 0,
		range: '2.0-14.0',
		changes: 0.1,
		companyName: 'Zura Bio Limited',
		currency: 'USD',
		cik: '0001855644',
		isin: null,
		cusip: null,
		exchange: 'NASDAQ Capital Market',
		exchangeShortName: 'NASDAQ',
		industry: 'Biotechnology',
		website: 'https://zurabio.com',
		description:
			'Zura Bio Limited, a clinical-stage biotechnology company, focuses on developing novel medicines for immune and inflammatory disorders. It develops ZB-168, an anti IL7R a inhibitor that impact on diseases driven by IL7 and TSLP biological pathways; and Torudokimab, a monoclonal antibody that neutralizes IL33, which is in Phase 2 clinical trial development. The company is based in San Diego, California.',
		ceo: 'Mr. Robert  Lisicki',
		sector: 'Healthcare',
		country: 'US',
		image: 'https://financialmodelingprep.com/image-stock/ZURA.png',
		type: 'stock',
		modifiedStocks: [
			{
				modifiedDate: createDateForStocksForThisWeek('Sat'),
				priceBefore: 49.8,
				priceAfter: 49.71,
				changes: -0.09,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Fri'),
				priceBefore: 46.8,
				priceAfter: 49.8,
				changes: 3,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Thu'),
				priceBefore: 54,
				priceAfter: 46.8,
				changes: -7.2,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Wed'),
				priceBefore: 53.94,
				priceAfter: 54,
				changes: 0.06,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Tue'),
				priceBefore: 54.9,
				priceAfter: 54.94,
				changes: 0.04,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Mon'),
				priceBefore: 54.8,
				priceAfter: 54.62,
				changes: -0.18,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Sun'),
				priceBefore: 54.62,
				priceAfter: 54.8,
				changes: 0.18,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-1),
				priceBefore: 52.62,
				priceAfter: 52.61,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-2),
				priceBefore: 52.63,
				priceAfter: 52.62,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-6),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('December'),
				priceBefore: 49,
				priceAfter: 54,
				changes: 5,
			},
			{
				modifiedDate: createDateForStocksForYear('August'),
				priceBefore: 60,
				priceAfter: 54,
				changes: -6,
			},
			{
				modifiedDate: createDateForStocksForYear('May'),
				priceBefore: 55,
				priceAfter: 54.63,
				changes: -0.37,
			},
			{
				modifiedDate: createDateForStocksForYear('June'),
				priceBefore: 54.68,
				priceAfter: 54.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('April'),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
		],
	},
	{
		symbol: 'PMT',
		price: 14.635,
		beta: 1.432,
		volAvg: 668651,
		mktCap: 1268070064,
		lastDiv: 1.6,
		range: '10.52-15.89',
		changes: 0.135,
		companyName: 'PennyMac Mortgage Investment Trust',
		currency: 'USD',
		cik: '0001464423',
		isin: 'US70931T1034',
		cusip: '70931T103',
		exchange: 'New York Stock Exchange',
		exchangeShortName: 'NYSE',
		industry: 'REIT - Mortgage',
		website: 'https://www.pennymacmortgageinvestmenttrust.com',
		description:
			"PennyMac Mortgage Investment Trust, a specialty finance company, primarily invests in mortgage-related assets in the United States. The company's Credit Sensitive Strategies segment invests in credit risk transfer (CRT) agreements, CRT securities, distressed loans, real estate, and non-agency subordinated bonds. Its Interest Rate Sensitive Strategies segment engages in investing in mortgage servicing rights, excess servicing spreads, and agency and senior non-agency mortgage-backed securities (MBS), as well as related interest rate hedging activities. The company's Correspondent Production segment is involved in purchasing, pooling, and reselling newly originated prime credit residential loans directly or in the form of MBS. PNMAC Capital Management, LLC acts as the manager of PennyMac Mortgage Investment Trust. The company qualifies as a real estate investment trust for federal income tax purposes. It generally would not be subject to federal corporate income taxes if it distributes at least 90% of its taxable income to its shareholders. PennyMac Mortgage Investment Trust was founded in 2009 and is headquartered in Westlake Village, California.",
		ceo: 'Mr. David A. Spector',
		sector: 'Real Estate',
		country: 'US',
		image: 'https://financialmodelingprep.com/image-stock/PMT.png',
		type: 'bound',
		modifiedStocks: [
			{
				modifiedDate: createDateForStocksForThisWeek('Sat'),
				priceBefore: 49.8,
				priceAfter: 49.71,
				changes: -0.09,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Fri'),
				priceBefore: 46.8,
				priceAfter: 49.8,
				changes: 3,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Thu'),
				priceBefore: 54,
				priceAfter: 46.8,
				changes: -7.2,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Wed'),
				priceBefore: 53.94,
				priceAfter: 54,
				changes: 0.06,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Tue'),
				priceBefore: 54.9,
				priceAfter: 54.94,
				changes: 0.04,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Mon'),
				priceBefore: 54.8,
				priceAfter: 54.62,
				changes: -0.18,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Sun'),
				priceBefore: 54.62,
				priceAfter: 54.8,
				changes: 0.18,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-1),
				priceBefore: 52.62,
				priceAfter: 52.61,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-2),
				priceBefore: 52.63,
				priceAfter: 52.62,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-6),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('December'),
				priceBefore: 49,
				priceAfter: 54,
				changes: 5,
			},
			{
				modifiedDate: createDateForStocksForYear('August'),
				priceBefore: 60,
				priceAfter: 54,
				changes: -6,
			},
			{
				modifiedDate: createDateForStocksForYear('May'),
				priceBefore: 55,
				priceAfter: 54.63,
				changes: -0.37,
			},
			{
				modifiedDate: createDateForStocksForYear('June'),
				priceBefore: 54.68,
				priceAfter: 54.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('April'),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
		],
	},
	{
		symbol: 'VGT',
		price: 509.0687,
		beta: 1.24,
		volAvg: 455920,
		mktCap: 80832787116,
		lastDiv: 3.6106999999999996,
		range: '380.18-536.63',
		changes: 13.0087,
		companyName: 'Vanguard Information Technology Index Fund',
		currency: 'USD',
		cik: '0000052848',
		isin: 'US92204A7028',
		cusip: '92204A702',
		exchange: 'New York Stock Exchange Arca',
		exchangeShortName: 'AMEX',
		industry: 'Asset Management',
		website: null,
		description:
			'The fund employs an indexing investment approach designed to track the performance of the MSCI US Investable Market Index/Information Technology 25/50, an index made up of stocks of large, mid-size, and small U.S. companies within the information technology sector, as classified under the Global Industry Classification Standard. The Advisor attempts to replicate the target index by seeking to invest all, or substantially all, of its assets in the stocks that make up the index, in order to hold each stock in approximately the same proportion as its weighting in the index. It is non-diversified.',
		ceo: '',
		sector: 'Financial Services',
		country: 'US',
		image: 'https://financialmodelingprep.com/image-stock/VGT.png',
		type: 'etf',
		modifiedStocks: [
			{
				modifiedDate: createDateForStocksForThisWeek('Sat'),
				priceBefore: 49.8,
				priceAfter: 49.71,
				changes: -0.09,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Fri'),
				priceBefore: 46.8,
				priceAfter: 49.8,
				changes: 3,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Thu'),
				priceBefore: 54,
				priceAfter: 46.8,
				changes: -7.2,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Wed'),
				priceBefore: 53.94,
				priceAfter: 54,
				changes: 0.06,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Tue'),
				priceBefore: 54.9,
				priceAfter: 54.94,
				changes: 0.04,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Mon'),
				priceBefore: 54.8,
				priceAfter: 54.62,
				changes: -0.18,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Sun'),
				priceBefore: 54.62,
				priceAfter: 54.8,
				changes: 0.18,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-1),
				priceBefore: 52.62,
				priceAfter: 52.61,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-2),
				priceBefore: 52.63,
				priceAfter: 52.62,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-6),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('December'),
				priceBefore: 49,
				priceAfter: 54,
				changes: 5,
			},
			{
				modifiedDate: createDateForStocksForYear('August'),
				priceBefore: 60,
				priceAfter: 54,
				changes: -6,
			},
			{
				modifiedDate: createDateForStocksForYear('May'),
				priceBefore: 55,
				priceAfter: 54.63,
				changes: -0.37,
			},
			{
				modifiedDate: createDateForStocksForYear('June'),
				priceBefore: 54.68,
				priceAfter: 54.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('April'),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
		],
	},
	{
		symbol: 'IWM',
		price: 201.81,
		beta: 1.04,
		volAvg: 35473159,
		mktCap: 56718695051,
		lastDiv: 2.5935699999999997,
		range: '161.67-211.88',
		changes: 1.89,
		companyName: 'iShares Russell 2000 ETF',
		currency: 'USD',
		cik: '0001100663',
		isin: 'US4642876555',
		cusip: '464287655',
		exchange: 'New York Stock Exchange Arca',
		exchangeShortName: 'AMEX',
		industry: 'Asset Management',
		website: 'https://www.ishares.com/us/products/239710/ishares-russell-2000-etf',
		description:
			'The fund generally invests at least 80% of its assets in the component securities of its underlying index and in investments that have economic characteristics that are substantially identical to the component securities of its underlying index (i.e., depositary receipts representing securities of the underlying index) and may invest up to 20% of its assets in certain futures, options and swap contracts, cash and cash equivalents.',
		ceo: '',
		sector: 'Financial Services',
		country: 'US',
		image: 'https://financialmodelingprep.com/image-stock/IWM.png',
		type: 'etf',
		modifiedStocks: [
			{
				modifiedDate: createDateForStocksForThisWeek('Sat'),
				priceBefore: 49.8,
				priceAfter: 49.71,
				changes: -0.09,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Fri'),
				priceBefore: 46.8,
				priceAfter: 49.8,
				changes: 3,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Thu'),
				priceBefore: 54,
				priceAfter: 46.8,
				changes: -7.2,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Wed'),
				priceBefore: 53.94,
				priceAfter: 54,
				changes: 0.06,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Tue'),
				priceBefore: 54.9,
				priceAfter: 54.94,
				changes: 0.04,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Mon'),
				priceBefore: 54.8,
				priceAfter: 54.62,
				changes: -0.18,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Sun'),
				priceBefore: 54.62,
				priceAfter: 54.8,
				changes: 0.18,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-1),
				priceBefore: 52.62,
				priceAfter: 52.61,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-2),
				priceBefore: 52.63,
				priceAfter: 52.62,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-6),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('December'),
				priceBefore: 49,
				priceAfter: 54,
				changes: 5,
			},
			{
				modifiedDate: createDateForStocksForYear('August'),
				priceBefore: 60,
				priceAfter: 54,
				changes: -6,
			},
			{
				modifiedDate: createDateForStocksForYear('May'),
				priceBefore: 55,
				priceAfter: 54.63,
				changes: -0.37,
			},
			{
				modifiedDate: createDateForStocksForYear('June'),
				priceBefore: 54.68,
				priceAfter: 54.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('April'),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
		],
	},
	{
		symbol: 'IYW',
		price: 132,
		beta: 1.26,
		volAvg: 905712,
		mktCap: 2725799736,
		lastDiv: 0.46595700000000007,
		range: '91.7-137.54',
		changes: 2.99,
		companyName: 'iShares U.S. Technology ETF',
		currency: 'USD',
		cik: '0001100663',
		isin: 'US4642877215',
		cusip: '464287721',
		exchange: 'New York Stock Exchange Arca',
		exchangeShortName: 'AMEX',
		industry: 'Asset Management',
		website: null,
		description:
			'The fund generally will invest at least 80% of its assets in the component securities of its underlying index and in investments that have economic characteristics that are substantially identical to the component securities of its underlying index. The underlying index measures the performance of the technology sector of the U.S. equity market, as defined by FTSE Russell. The fund is non-diversified.',
		ceo: '',
		sector: 'Financial Services',
		country: 'US',
		image: 'https://financialmodelingprep.com/image-stock/IYW.png',
		type: 'etf',
		modifiedStocks: [
			{
				modifiedDate: createDateForStocksForThisWeek('Sat'),
				priceBefore: 49.8,
				priceAfter: 49.71,
				changes: -0.09,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Fri'),
				priceBefore: 46.8,
				priceAfter: 49.8,
				changes: 3,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Thu'),
				priceBefore: 54,
				priceAfter: 46.8,
				changes: -7.2,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Wed'),
				priceBefore: 53.94,
				priceAfter: 54,
				changes: 0.06,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Tue'),
				priceBefore: 54.9,
				priceAfter: 54.94,
				changes: 0.04,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Mon'),
				priceBefore: 54.8,
				priceAfter: 54.62,
				changes: -0.18,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Sun'),
				priceBefore: 54.62,
				priceAfter: 54.8,
				changes: 0.18,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-1),
				priceBefore: 52.62,
				priceAfter: 52.61,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-2),
				priceBefore: 52.63,
				priceAfter: 52.62,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-6),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('December'),
				priceBefore: 49,
				priceAfter: 54,
				changes: 5,
			},
			{
				modifiedDate: createDateForStocksForYear('August'),
				priceBefore: 60,
				priceAfter: 54,
				changes: -6,
			},
			{
				modifiedDate: createDateForStocksForYear('May'),
				priceBefore: 55,
				priceAfter: 54.63,
				changes: -0.37,
			},
			{
				modifiedDate: createDateForStocksForYear('June'),
				priceBefore: 54.68,
				priceAfter: 54.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('April'),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
		],
	},
	{
		symbol: 'SOXX',
		price: 216.19,
		beta: 1.63,
		volAvg: 4122927,
		mktCap: 1653853500,
		lastDiv: 3.66466,
		range: '134.77333-240.01',
		changes: 4.78,
		companyName: 'iShares Semiconductor ETF',
		currency: 'USD',
		cik: '0001100663',
		isin: 'US4642875235',
		cusip: '464287523',
		exchange: 'NASDAQ Global Market',
		exchangeShortName: 'NASDAQ',
		industry: 'Asset Management',
		website: null,
		description:
			'The fund generally will invest at least 80% of its assets in the component securities of its index and in investments that have economic characteristics that are substantially identical to the component securities of its index and may invest up to 20% of its assets in certain futures, options and swap contracts, cash and cash equivalents. The fund is non-diversified.',
		ceo: '',
		sector: 'Financial Services',
		country: 'US',
		image: 'https://financialmodelingprep.com/image-stock/SOXX.png',
		type: 'etf',
		modifiedStocks: [
			{
				modifiedDate: createDateForStocksForThisWeek('Sat'),
				priceBefore: 49.8,
				priceAfter: 49.71,
				changes: -0.09,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Fri'),
				priceBefore: 46.8,
				priceAfter: 49.8,
				changes: 3,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Thu'),
				priceBefore: 54,
				priceAfter: 46.8,
				changes: -7.2,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Wed'),
				priceBefore: 53.94,
				priceAfter: 54,
				changes: 0.06,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Tue'),
				priceBefore: 54.9,
				priceAfter: 54.94,
				changes: 0.04,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Mon'),
				priceBefore: 54.8,
				priceAfter: 54.62,
				changes: -0.18,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Sun'),
				priceBefore: 54.62,
				priceAfter: 54.8,
				changes: 0.18,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-1),
				priceBefore: 52.62,
				priceAfter: 52.61,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-2),
				priceBefore: 52.63,
				priceAfter: 52.62,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-6),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('December'),
				priceBefore: 49,
				priceAfter: 54,
				changes: 5,
			},
			{
				modifiedDate: createDateForStocksForYear('August'),
				priceBefore: 60,
				priceAfter: 54,
				changes: -6,
			},
			{
				modifiedDate: createDateForStocksForYear('May'),
				priceBefore: 55,
				priceAfter: 54.63,
				changes: -0.37,
			},
			{
				modifiedDate: createDateForStocksForYear('June'),
				priceBefore: 54.68,
				priceAfter: 54.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('April'),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
		],
	},
	{
		symbol: 'SQQQ',
		price: 11.1091,
		beta: -3.52,
		volAvg: 140557946,
		mktCap: 2881603969,
		lastDiv: 1.0371,
		range: '10.05-30.25',
		changes: -0.6709,
		companyName: 'ProShares UltraPro Short QQQ',
		currency: 'USD',
		cik: '0001174610',
		isin: 'US74347G4322',
		cusip: null,
		exchange: 'NASDAQ Global Market',
		exchangeShortName: 'NASDAQ',
		industry: 'Asset Management',
		website: null,
		description:
			"The fund invests in financial instruments that ProShare Advisors believes, in combination, should produce daily returns consistent with the fund's investment objective. The index includes 100 of the largest domestic and international non-financial companies listed on The Nasdaq Stock Market based on market capitalization. The fund is non-diversified.",
		ceo: '',
		sector: 'Financial Services',
		country: 'US',
		image: 'https://financialmodelingprep.com/image-stock/SQQQ.png',
		type: 'etf',
		modifiedStocks: [
			{
				modifiedDate: createDateForStocksForThisWeek('Sat'),
				priceBefore: 49.8,
				priceAfter: 49.71,
				changes: -0.09,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Fri'),
				priceBefore: 46.8,
				priceAfter: 49.8,
				changes: 3,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Thu'),
				priceBefore: 54,
				priceAfter: 46.8,
				changes: -7.2,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Wed'),
				priceBefore: 53.94,
				priceAfter: 54,
				changes: 0.06,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Tue'),
				priceBefore: 54.9,
				priceAfter: 54.94,
				changes: 0.04,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Mon'),
				priceBefore: 54.8,
				priceAfter: 54.62,
				changes: -0.18,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Sun'),
				priceBefore: 54.62,
				priceAfter: 54.8,
				changes: 0.18,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-1),
				priceBefore: 52.62,
				priceAfter: 52.61,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-2),
				priceBefore: 52.63,
				priceAfter: 52.62,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-6),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('December'),
				priceBefore: 49,
				priceAfter: 54,
				changes: 5,
			},
			{
				modifiedDate: createDateForStocksForYear('August'),
				priceBefore: 60,
				priceAfter: 54,
				changes: -6,
			},
			{
				modifiedDate: createDateForStocksForYear('May'),
				priceBefore: 55,
				priceAfter: 54.63,
				changes: -0.37,
			},
			{
				modifiedDate: createDateForStocksForYear('June'),
				priceBefore: 54.68,
				priceAfter: 54.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('April'),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
		],
	},
	{
		symbol: 'AAPL',
		price: 184.8299,
		beta: 1.276,
		volAvg: 61548179,
		mktCap: 2854124832810,
		lastDiv: 0.96,
		range: '164.08-199.62',
		changes: 11.7999,
		companyName: 'Apple Inc.',
		currency: 'USD',
		cik: '0000320193',
		isin: 'US0378331005',
		cusip: '037833100',
		exchange: 'NASDAQ Global Select',
		exchangeShortName: 'NASDAQ',
		industry: 'Consumer Electronics',
		website: 'https://www.apple.com',
		description:
			'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, and HomePod. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts. In addition, the company offers various services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV+, which offers exclusive original content; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. Apple Inc. was incorporated in 1977 and is headquartered in Cupertino, California.',
		ceo: 'Mr. Timothy D. Cook',
		sector: 'Technology',
		country: 'US',
		image: 'https://financialmodelingprep.com/image-stock/AAPL.png',
		type: 'stock',
		modifiedStocks: [
			{
				modifiedDate: createDateForStocksForThisWeek('Sat'),
				priceBefore: 49.8,
				priceAfter: 49.71,
				changes: -0.09,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Fri'),
				priceBefore: 46.8,
				priceAfter: 49.8,
				changes: 3,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Thu'),
				priceBefore: 54,
				priceAfter: 46.8,
				changes: -7.2,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Wed'),
				priceBefore: 53.94,
				priceAfter: 54,
				changes: 0.06,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Tue'),
				priceBefore: 54.9,
				priceAfter: 54.94,
				changes: 0.04,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Mon'),
				priceBefore: 54.8,
				priceAfter: 54.62,
				changes: -0.18,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Sun'),
				priceBefore: 54.62,
				priceAfter: 54.8,
				changes: 0.18,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-1),
				priceBefore: 52.62,
				priceAfter: 52.61,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-2),
				priceBefore: 52.63,
				priceAfter: 52.62,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-6),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('December'),
				priceBefore: 49,
				priceAfter: 54,
				changes: 5,
			},
			{
				modifiedDate: createDateForStocksForYear('August'),
				priceBefore: 60,
				priceAfter: 54,
				changes: -6,
			},
			{
				modifiedDate: createDateForStocksForYear('May'),
				priceBefore: 55,
				priceAfter: 54.63,
				changes: -0.37,
			},
			{
				modifiedDate: createDateForStocksForYear('June'),
				priceBefore: 54.68,
				priceAfter: 54.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('April'),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
		],
	},
	{
		symbol: 'AMAL',
		price: 25.49,
		beta: 0.931,
		volAvg: 153553,
		mktCap: 777450098,
		lastDiv: 0.48,
		range: '14.05-27.77',
		changes: 0.3,
		companyName: 'Amalgamated Financial Corp.',
		currency: 'USD',
		cik: '0001823608',
		isin: 'US0226711010',
		cusip: '022671101',
		exchange: 'NASDAQ Global Market',
		exchangeShortName: 'NASDAQ',
		industry: 'Banks - Regional',
		website: 'https://www.amalgamatedbank.com',
		description:
			'Amalgamated Financial Corp. operates as the bank holding company for Amalgamated Bank that provides commercial and retail banking, investment management, and trust and custody services for commercial and retail customers in the United States. The company accepts various deposit products, including non-interest bearing accounts, interest-bearing demand products, savings accounts, money market accounts, NOW accounts, and certificates of deposit. It also provides various commercial loans comprising commercial and industrial, multifamily mortgage, and commercial real estate loans; and retail loans, such as residential real estate, and consumer and other loans. In addition, the company offers online banking, bill payment, online cash management, and safe deposit box rental services; debit and ATM cards; and trust, custody, and investment management services comprising asset safekeeping, corporate actions, income collections, proxy, account transition, asset transfers, and conversion management services. Further, it provides investment products, such as equity, fixed-income, real estate, and alternative investment products; and brokerage, asset management, and insurance products. The company operates through its three branch offices across New York City, one branch office in Washington, D.C., one branch office in San Francisco, one commercial office in Boston, and digital banking platform. Amalgamated Financial Corp. was founded in 1923 and is headquartered in New York, New York.',
		ceo: 'Ms. Priscilla Sims Brown',
		sector: 'Financial Services',
		country: 'US',
		image: 'https://financialmodelingprep.com/image-stock/AMAL.png',
		type: 'stock',
		modifiedStocks: [
			{
				modifiedDate: createDateForStocksForThisWeek('Sat'),
				priceBefore: 49.8,
				priceAfter: 49.71,
				changes: -0.09,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Fri'),
				priceBefore: 46.8,
				priceAfter: 49.8,
				changes: 3,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Thu'),
				priceBefore: 54,
				priceAfter: 46.8,
				changes: -7.2,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Wed'),
				priceBefore: 53.94,
				priceAfter: 54,
				changes: 0.06,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Tue'),
				priceBefore: 54.9,
				priceAfter: 54.94,
				changes: 0.04,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Mon'),
				priceBefore: 54.8,
				priceAfter: 54.62,
				changes: -0.18,
			},
			{
				modifiedDate: createDateForStocksForThisWeek('Sun'),
				priceBefore: 54.62,
				priceAfter: 54.8,
				changes: 0.18,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-1),
				priceBefore: 52.62,
				priceAfter: 52.61,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-2),
				priceBefore: 52.63,
				priceAfter: 52.62,
				changes: -0.01,
			},
			{
				modifiedDate: createDateForStocksForThisDay(-6),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('December'),
				priceBefore: 49,
				priceAfter: 54,
				changes: 5,
			},
			{
				modifiedDate: createDateForStocksForYear('August'),
				priceBefore: 60,
				priceAfter: 54,
				changes: -6,
			},
			{
				modifiedDate: createDateForStocksForYear('May'),
				priceBefore: 55,
				priceAfter: 54.63,
				changes: -0.37,
			},
			{
				modifiedDate: createDateForStocksForYear('June'),
				priceBefore: 54.68,
				priceAfter: 54.63,
				changes: -0.05,
			},
			{
				modifiedDate: createDateForStocksForYear('April'),
				priceBefore: 52.68,
				priceAfter: 52.63,
				changes: -0.05,
			},
		],
	},
];
